kind: pipeline
name: default

steps:
- name: test
  image: rancher/ui:build
  commands:
  - ./scripts/ci
  volumes:
  - name: cache
    path: /var/cache/npm
  when:
    event:
    - pull_request

- name: build
  image: rancher/ui:build
  commands:
  - BUILD_LATEST=true ./scripts/ci
  - tar -jcvf ui.tar.bz2 dist/static/latest2/
  volumes:
  - name: cache
    path: /var/cache/npm
  when:
    event: tag

- name: upload
  image: plugins/github-release
  settings:
    api_key:
      from_secret: git_release
    files: ui.tar.bz2
    when:
      event: tag

volumes:
- name: cache
  temp: {}
