---
pipeline:
  test:
    image: rancher/ui:build
    commands:
      - ./scripts/ci
    volumes:
      - /tmp/cache-npm:/var/cache/npm
    when:
      event:
        - pull_request

  build:
    image: rancher/ui:build
    commands:
      - BUILD_LATEST=true ./scripts/ci
    volumes:
      - /tmp/cache-npm:/var/cache/npm
    when:
      event: tag

  upload:
    image: plugins/github-release
      settings:
        api_key:
          from_secret: git_release
        files: dist/static/latest2/*
        when:
          event: tag
