kind: pipeline
name: default

steps:
- name: test
  image: rancher/ui:build
  commands:
     - ./scripts/ci
  volumes:
     - name: cache
       path: /var/cache/npm
  when:
    event:
      - pull_request

volumes:
  - name: cache
    host:
      path: /tmp/cache-npm

- name: build
  image: rancher/ui:build
  commands:
     - BUILD_LATEST=true ./scripts/ci
  volumes:
    - name: cache
      path: /var/cache/npm
  when:
    event: tag

- name: upload
  image: plugins/github-release
  settings:
    api_key:
      from_secret: git_release
    files: dist/static/latest2/*
    when:
      event: tag
